### ISSUE TITLE
API 명세 문의

### ISSUE THREAD

**Issue by palindrom615** [iamport/iamport-cordova#12]
https://cdn.iamport.kr/js/iamport.payment-1.1.5.js js 라이브러리와 비교했을때, `IMP.request_pay` API가  `cordova.plugins.IamportCordova.payment`와 대응되는 것이 맞을까요?

**Comment by palindrom615** [comment]
추가로 콜백함수 명세에 관해서,

https://github.com/iamport/iamport-cordova/blob/master/manuals/CALLBACK.md

위 문서에서는 `request_pay` API의 콜백 함수와 같은 rsp 객체를 사용한다고 적혀있는데 `success` -> `imp_success` 등 이름이 다른 키 값이 더러 있는 것 같습니다. 확인 부탁드립니다.

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

1. https://cdn.iamport.kr/js/iamport.payment-1.1.5.js js 라이브러리와 비교했을때, IMP.request_pay API cordova.plugins.IamportCordova.payment와 대응되는 것이 맞을까요?
네 맞습니다.

2. 콜백함수 명세에 관해서, https://github.com/iamport/iamport-cordova/blob/master/manuals/CALLBACK.md
위 문서에서는 request_pay API의 콜백 함수와 같은 rsp 객체를 사용한다고 적혀있는데 success -> imp_success 등 이름이 다른 키 값이 더러 있는 것 같습니다. 확인 부탁드립니다.
아임포트 모바일용 프레임워크(iamport-cordova 포함)는 모두 내부적으로 웹뷰를 띄운 후 아임포트 JS SDK 함수를 사용하고 있어 모든 스펙은 이를 따라갑니다.
아임포트가 확장해나가면서 PG사를 하나씩 연동하다가 어떤 PG사는 `imp_success`를, 또 다른 PG사는 `success` 파라미터를 내려보내게 되었고 기존 사용자의 호환성을 고려해 이를 수정하지 못했습니다.
따라서 아임포트 모바일용 프레임워크에서는 이를 모두 [하나의 파라미터(imp_success)로 통일](https://github.com/iamport/iamport-cordova/blob/master/www/IamportCordova.js#L54)해서 내려보내고 있으니 참고 부탁드립니다.
추가적으로 `imp_success` 파라미터로 결제 성공(status: `paid`) 여부를 판단하시면 안되고 가맹점 웹서버 단에서 아임포트 결제내역 조회 API([GET /payments/{imp_uid}](https://api.iamport.kr/#!/payments/getPaymentByImpUid)) 호출을 통해 결제 금액 위/변조 여부 확인을 통해 판단하셔야 합니다.
이에 대한 자세한 내용은 [imp_success 파라미터](https://github.com/iamport/iamport-cordova/blob/master/manuals/CALLBACK.md#imp-success-%ED%8C%8C%EB%9D%BC%EB%AF%B8%ED%84%B0) 그리고 [일반결제 연동하기 > 결제 위변조 여부 검증 후 데이터 동기화하기](https://docs.iamport.kr/implementation/payment#server-side-logic-3)를 참고해주세요.

감사합니다.
