### ISSUE TITLE
가이드를 좀 쉽게 달아주실수 없나요?

### ISSUE THREAD

**Issue by kimjongkyun** [iamport/iamport-cordova#2]
가이드를 좀 쉽게 달아주실수 없나요?

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

혹시 어떤 부분에서 어려움을 느끼셨을까요?

궁금하신 사항을 문의주시면 안내 도와드리겠습니다.

감사합니다.
