### ISSUE TITLE
결제모듈이 작동하지 않습니다.

### ISSUE THREAD

**Issue by MartianLee** [iamport/iamport-cordova#8]
아임포트로 카카오페이 결제를 시도하려고 하고 있는데, iOS 아무것도 뜨지 않고 , Android는 웹페이지를 로딩할 수 없다는 문제가 생깁니다.
무엇을 잘못 설정해서 그런 것일까요? 도움을 부탁드립니다 🙏

![Image from iOS](https://user-images.githubusercontent.com/1390368/91703594-65ef2200-ebb5-11ea-9c23-3e761b8d3d3f.png)
![Screenshot_20200831-163727](https://user-images.githubusercontent.com/1390368/91703626-743d3e00-ebb5-11ea-8c8a-9917d1061579.jpg)

```
declare var cordova: any;

      // 사용
      const params = {
        titleOptions: titleOptions,                   // 타이틀 옵션
        userCode: userCode,                           // 가맹점 식별코드
        data: data,                                   // 결제 데이터
        callback: this.donePayment,                           // 콜백 함수
      }
```
각각의 titleOption, userCode, data를 정확히 입력한 것을 확인하였구요, PC웹에서는 카카오페이 창이 잘 떠서 바코드로 결제를 성공하였습니다. 모바일에서 시도하려고 하니 잘 되질 않네요. 무엇이 문제일까요?

패키지 버전정보
```
"@angular/core": "~9.1.6",
"iamport-cordova": "^0.9.6",
```

**Comment by SoleeChoi** [comment]
안녕하세요 아임포트 기술지원팀입니다.

iamport-cordova 플러그인을 [설치](https://github.com/iamport/iamport-cordova#%EC%84%A4%EC%B9%98%ED%95%98%EA%B8%B0)하면
귀하의 프로젝트에 [웹뷰 리소스 파일을 자동으로 추가](https://github.com/iamport/iamport-cordova/blob/master/plugin.xml#L17) 하도록 되어있는데, 설치하는 과정에서 이 부분이 제대로 되지 않은 것 같습니다.

아래 경로에 해당 파일이 있는지 확인 부탁드립니다.
- 안드로이드: platforms/android/app/src/main/assets/www/iamport-webview.html
- IOS: platforms/ios/www/iamport-webview.html

감사합니다.

**Comment by MartianLee** [comment]
빠른 답변 감사합니다. 여러 다른 방법을 시도하다가 import-capacitor 프로젝트가 있어서 그 라이브러리를 import했더니 다행히 잘 작동하였습니다. 감사합니다!!!!
